#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pakistan_International_Airlines
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database2")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRegistration(Registration instance);
    partial void UpdateRegistration(Registration instance);
    partial void DeleteRegistration(Registration instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Pakistan_International_Airlines.Properties.Settings.Default.Database2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AddFlight> AddFlights
		{
			get
			{
				return this.GetTable<AddFlight>();
			}
		}
		
		public System.Data.Linq.Table<MultiCity> MultiCities
		{
			get
			{
				return this.GetTable<MultiCity>();
			}
		}
		
		public System.Data.Linq.Table<OneWay> OneWays
		{
			get
			{
				return this.GetTable<OneWay>();
			}
		}
		
		public System.Data.Linq.Table<Registration> Registrations
		{
			get
			{
				return this.GetTable<Registration>();
			}
		}
		
		public System.Data.Linq.Table<RoundTrip> RoundTrips
		{
			get
			{
				return this.GetTable<RoundTrip>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AddFlight")]
	public partial class AddFlight
	{
		
		private string _FlightNo;
		
		private string _tb_From;
		
		private string _tb_To;
		
		private System.Nullable<System.DateTime> _Departure;
		
		private string _GoingTime;
		
		private string _LandingTime;
		
		private System.Nullable<int> _Price;
		
		private string _FlightClass;
		
		public AddFlight()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightNo", DbType="VarChar(50)")]
		public string FlightNo
		{
			get
			{
				return this._FlightNo;
			}
			set
			{
				if ((this._FlightNo != value))
				{
					this._FlightNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_From", DbType="VarChar(50)")]
		public string tb_From
		{
			get
			{
				return this._tb_From;
			}
			set
			{
				if ((this._tb_From != value))
				{
					this._tb_From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_To", DbType="VarChar(50)")]
		public string tb_To
		{
			get
			{
				return this._tb_To;
			}
			set
			{
				if ((this._tb_To != value))
				{
					this._tb_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departure", DbType="Date")]
		public System.Nullable<System.DateTime> Departure
		{
			get
			{
				return this._Departure;
			}
			set
			{
				if ((this._Departure != value))
				{
					this._Departure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoingTime", DbType="VarChar(50)")]
		public string GoingTime
		{
			get
			{
				return this._GoingTime;
			}
			set
			{
				if ((this._GoingTime != value))
				{
					this._GoingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandingTime", DbType="VarChar(50)")]
		public string LandingTime
		{
			get
			{
				return this._LandingTime;
			}
			set
			{
				if ((this._LandingTime != value))
				{
					this._LandingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightClass", DbType="VarChar(50)")]
		public string FlightClass
		{
			get
			{
				return this._FlightClass;
			}
			set
			{
				if ((this._FlightClass != value))
				{
					this._FlightClass = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MultiCity")]
	public partial class MultiCity
	{
		
		private string _Flight1_FlightNo;
		
		private string _Flight1_From;
		
		private string _Flight1_To;
		
		private System.Nullable<System.DateTime> _Flight1_Departure;
		
		private string _Flight1_GoingTime;
		
		private string _Flight1_LandingTime;
		
		private string _Flight2_FlightNo;
		
		private string _Flight2_From;
		
		private string _Flight2_To;
		
		private System.Nullable<System.DateTime> _Flight2_Departure;
		
		private string _Flight2_GoingTime;
		
		private string _Flight2_LandingTime;
		
		private System.Nullable<int> _Adult;
		
		private System.Nullable<int> _Chlid;
		
		private System.Nullable<int> _Inflant;
		
		private string _FlightClass;
		
		private System.Nullable<int> _Price;
		
		private string _Email;
		
		public MultiCity()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight1_FlightNo", DbType="VarChar(50)")]
		public string Flight1_FlightNo
		{
			get
			{
				return this._Flight1_FlightNo;
			}
			set
			{
				if ((this._Flight1_FlightNo != value))
				{
					this._Flight1_FlightNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight1_From", DbType="VarChar(50)")]
		public string Flight1_From
		{
			get
			{
				return this._Flight1_From;
			}
			set
			{
				if ((this._Flight1_From != value))
				{
					this._Flight1_From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight1_To", DbType="VarChar(50)")]
		public string Flight1_To
		{
			get
			{
				return this._Flight1_To;
			}
			set
			{
				if ((this._Flight1_To != value))
				{
					this._Flight1_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight1_Departure", DbType="Date")]
		public System.Nullable<System.DateTime> Flight1_Departure
		{
			get
			{
				return this._Flight1_Departure;
			}
			set
			{
				if ((this._Flight1_Departure != value))
				{
					this._Flight1_Departure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight1_GoingTime", DbType="VarChar(50)")]
		public string Flight1_GoingTime
		{
			get
			{
				return this._Flight1_GoingTime;
			}
			set
			{
				if ((this._Flight1_GoingTime != value))
				{
					this._Flight1_GoingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight1_LandingTime", DbType="VarChar(50)")]
		public string Flight1_LandingTime
		{
			get
			{
				return this._Flight1_LandingTime;
			}
			set
			{
				if ((this._Flight1_LandingTime != value))
				{
					this._Flight1_LandingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight2_FlightNo", DbType="VarChar(50)")]
		public string Flight2_FlightNo
		{
			get
			{
				return this._Flight2_FlightNo;
			}
			set
			{
				if ((this._Flight2_FlightNo != value))
				{
					this._Flight2_FlightNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight2_From", DbType="VarChar(50)")]
		public string Flight2_From
		{
			get
			{
				return this._Flight2_From;
			}
			set
			{
				if ((this._Flight2_From != value))
				{
					this._Flight2_From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight2_To", DbType="VarChar(50)")]
		public string Flight2_To
		{
			get
			{
				return this._Flight2_To;
			}
			set
			{
				if ((this._Flight2_To != value))
				{
					this._Flight2_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight2_Departure", DbType="Date")]
		public System.Nullable<System.DateTime> Flight2_Departure
		{
			get
			{
				return this._Flight2_Departure;
			}
			set
			{
				if ((this._Flight2_Departure != value))
				{
					this._Flight2_Departure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight2_GoingTime", DbType="VarChar(50)")]
		public string Flight2_GoingTime
		{
			get
			{
				return this._Flight2_GoingTime;
			}
			set
			{
				if ((this._Flight2_GoingTime != value))
				{
					this._Flight2_GoingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight2_LandingTime", DbType="VarChar(50)")]
		public string Flight2_LandingTime
		{
			get
			{
				return this._Flight2_LandingTime;
			}
			set
			{
				if ((this._Flight2_LandingTime != value))
				{
					this._Flight2_LandingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adult", DbType="Int")]
		public System.Nullable<int> Adult
		{
			get
			{
				return this._Adult;
			}
			set
			{
				if ((this._Adult != value))
				{
					this._Adult = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chlid", DbType="Int")]
		public System.Nullable<int> Chlid
		{
			get
			{
				return this._Chlid;
			}
			set
			{
				if ((this._Chlid != value))
				{
					this._Chlid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inflant", DbType="Int")]
		public System.Nullable<int> Inflant
		{
			get
			{
				return this._Inflant;
			}
			set
			{
				if ((this._Inflant != value))
				{
					this._Inflant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightClass", DbType="VarChar(50)")]
		public string FlightClass
		{
			get
			{
				return this._FlightClass;
			}
			set
			{
				if ((this._FlightClass != value))
				{
					this._FlightClass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OneWay")]
	public partial class OneWay
	{
		
		private int _Id;
		
		private string _FlightNo;
		
		private string _tb_From;
		
		private string _tb_To;
		
		private System.Nullable<System.DateTime> _Departure;
		
		private System.Nullable<int> _Adult;
		
		private System.Nullable<int> _Chlid;
		
		private System.Nullable<int> _Inflant;
		
		private string _FlightClass;
		
		private string _GoingTime;
		
		private string _LandingTime;
		
		private System.Nullable<int> _Price;
		
		private string _Email;
		
		public OneWay()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightNo", DbType="VarChar(50)")]
		public string FlightNo
		{
			get
			{
				return this._FlightNo;
			}
			set
			{
				if ((this._FlightNo != value))
				{
					this._FlightNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_From", DbType="VarChar(50)")]
		public string tb_From
		{
			get
			{
				return this._tb_From;
			}
			set
			{
				if ((this._tb_From != value))
				{
					this._tb_From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_To", DbType="VarChar(50)")]
		public string tb_To
		{
			get
			{
				return this._tb_To;
			}
			set
			{
				if ((this._tb_To != value))
				{
					this._tb_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departure", DbType="Date")]
		public System.Nullable<System.DateTime> Departure
		{
			get
			{
				return this._Departure;
			}
			set
			{
				if ((this._Departure != value))
				{
					this._Departure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adult", DbType="Int")]
		public System.Nullable<int> Adult
		{
			get
			{
				return this._Adult;
			}
			set
			{
				if ((this._Adult != value))
				{
					this._Adult = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chlid", DbType="Int")]
		public System.Nullable<int> Chlid
		{
			get
			{
				return this._Chlid;
			}
			set
			{
				if ((this._Chlid != value))
				{
					this._Chlid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inflant", DbType="Int")]
		public System.Nullable<int> Inflant
		{
			get
			{
				return this._Inflant;
			}
			set
			{
				if ((this._Inflant != value))
				{
					this._Inflant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightClass", DbType="VarChar(50)")]
		public string FlightClass
		{
			get
			{
				return this._FlightClass;
			}
			set
			{
				if ((this._FlightClass != value))
				{
					this._FlightClass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoingTime", DbType="VarChar(50)")]
		public string GoingTime
		{
			get
			{
				return this._GoingTime;
			}
			set
			{
				if ((this._GoingTime != value))
				{
					this._GoingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LandingTime", DbType="VarChar(50)")]
		public string LandingTime
		{
			get
			{
				return this._LandingTime;
			}
			set
			{
				if ((this._LandingTime != value))
				{
					this._LandingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registration")]
	public partial class Registration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserNAME;
		
		private string _Email;
		
		private string _Password;
		
		private string _MobileNo;
		
		private string _Age;
		
		private string _Gender;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserNAMEChanging(string value);
    partial void OnUserNAMEChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnAgeChanging(string value);
    partial void OnAgeChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    #endregion
		
		public Registration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNAME", DbType="VarChar(50)")]
		public string UserNAME
		{
			get
			{
				return this._UserNAME;
			}
			set
			{
				if ((this._UserNAME != value))
				{
					this.OnUserNAMEChanging(value);
					this.SendPropertyChanging();
					this._UserNAME = value;
					this.SendPropertyChanged("UserNAME");
					this.OnUserNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="VarChar(50)")]
		public string MobileNo
		{
			get
			{
				return this._MobileNo;
			}
			set
			{
				if ((this._MobileNo != value))
				{
					this.OnMobileNoChanging(value);
					this.SendPropertyChanging();
					this._MobileNo = value;
					this.SendPropertyChanged("MobileNo");
					this.OnMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="VarChar(30)")]
		public string Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(30)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RoundTrip")]
	public partial class RoundTrip
	{
		
		private string _RoundTrip_FlightNo;
		
		private string _RoundTrip_tb_From;
		
		private string _RoundTrip_tb_To;
		
		private System.Nullable<System.DateTime> _RoundTrip_Departure;
		
		private string _RoundTrip_GoingTime;
		
		private string _RoundTrip_LandingTime;
		
		private string _Return_FlightNo;
		
		private string _Return_tb_From;
		
		private string _Return_tb_To;
		
		private System.Nullable<System.DateTime> _Return_Departure;
		
		private string _Return_GoingTime;
		
		private string _Return_LandingTime;
		
		private System.Nullable<int> _Adult;
		
		private System.Nullable<int> _Chlid;
		
		private System.Nullable<int> _Inflant;
		
		private string _FlightClass;
		
		private System.Nullable<int> _Price;
		
		private string _Email;
		
		public RoundTrip()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoundTrip_FlightNo", DbType="VarChar(50)")]
		public string RoundTrip_FlightNo
		{
			get
			{
				return this._RoundTrip_FlightNo;
			}
			set
			{
				if ((this._RoundTrip_FlightNo != value))
				{
					this._RoundTrip_FlightNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoundTrip_tb_From", DbType="VarChar(50)")]
		public string RoundTrip_tb_From
		{
			get
			{
				return this._RoundTrip_tb_From;
			}
			set
			{
				if ((this._RoundTrip_tb_From != value))
				{
					this._RoundTrip_tb_From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoundTrip_tb_To", DbType="VarChar(50)")]
		public string RoundTrip_tb_To
		{
			get
			{
				return this._RoundTrip_tb_To;
			}
			set
			{
				if ((this._RoundTrip_tb_To != value))
				{
					this._RoundTrip_tb_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoundTrip_Departure", DbType="Date")]
		public System.Nullable<System.DateTime> RoundTrip_Departure
		{
			get
			{
				return this._RoundTrip_Departure;
			}
			set
			{
				if ((this._RoundTrip_Departure != value))
				{
					this._RoundTrip_Departure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoundTrip_GoingTime", DbType="VarChar(50)")]
		public string RoundTrip_GoingTime
		{
			get
			{
				return this._RoundTrip_GoingTime;
			}
			set
			{
				if ((this._RoundTrip_GoingTime != value))
				{
					this._RoundTrip_GoingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoundTrip_LandingTime", DbType="VarChar(50)")]
		public string RoundTrip_LandingTime
		{
			get
			{
				return this._RoundTrip_LandingTime;
			}
			set
			{
				if ((this._RoundTrip_LandingTime != value))
				{
					this._RoundTrip_LandingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_FlightNo", DbType="VarChar(50)")]
		public string Return_FlightNo
		{
			get
			{
				return this._Return_FlightNo;
			}
			set
			{
				if ((this._Return_FlightNo != value))
				{
					this._Return_FlightNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_tb_From", DbType="VarChar(50)")]
		public string Return_tb_From
		{
			get
			{
				return this._Return_tb_From;
			}
			set
			{
				if ((this._Return_tb_From != value))
				{
					this._Return_tb_From = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_tb_To", DbType="VarChar(50)")]
		public string Return_tb_To
		{
			get
			{
				return this._Return_tb_To;
			}
			set
			{
				if ((this._Return_tb_To != value))
				{
					this._Return_tb_To = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_Departure", DbType="Date")]
		public System.Nullable<System.DateTime> Return_Departure
		{
			get
			{
				return this._Return_Departure;
			}
			set
			{
				if ((this._Return_Departure != value))
				{
					this._Return_Departure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_GoingTime", DbType="VarChar(50)")]
		public string Return_GoingTime
		{
			get
			{
				return this._Return_GoingTime;
			}
			set
			{
				if ((this._Return_GoingTime != value))
				{
					this._Return_GoingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_LandingTime", DbType="VarChar(50)")]
		public string Return_LandingTime
		{
			get
			{
				return this._Return_LandingTime;
			}
			set
			{
				if ((this._Return_LandingTime != value))
				{
					this._Return_LandingTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adult", DbType="Int")]
		public System.Nullable<int> Adult
		{
			get
			{
				return this._Adult;
			}
			set
			{
				if ((this._Adult != value))
				{
					this._Adult = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chlid", DbType="Int")]
		public System.Nullable<int> Chlid
		{
			get
			{
				return this._Chlid;
			}
			set
			{
				if ((this._Chlid != value))
				{
					this._Chlid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inflant", DbType="Int")]
		public System.Nullable<int> Inflant
		{
			get
			{
				return this._Inflant;
			}
			set
			{
				if ((this._Inflant != value))
				{
					this._Inflant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlightClass", DbType="VarChar(50)")]
		public string FlightClass
		{
			get
			{
				return this._FlightClass;
			}
			set
			{
				if ((this._FlightClass != value))
				{
					this._FlightClass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
